In [8]:
import numpy as np
import random

In [9]:
np.random.random(1)

array([0.66834806])

In [10]:
np.random.random((3, 3))

array([[0.79834984, 0.16273896, 0.74019244],
       [0.41641393, 0.77693105, 0.81466571],
       [0.24300781, 0.93004392, 0.03092339]])

In [12]:
np.random.randint(1, 4)

1

In [13]:
np.random.randint(1, 4, (4, 4))

array([[2, 1, 3, 2],
       [2, 3, 2, 3],
       [1, 1, 3, 1],
       [2, 3, 2, 2]])

In [16]:
np.random.randint(1, 7, (2, 4, 4))

array([[[2, 1, 3, 3],
        [2, 6, 3, 2],
        [4, 4, 6, 1],
        [4, 3, 1, 5]],

       [[3, 4, 5, 4],
        [2, 1, 5, 4],
        [5, 5, 2, 5],
        [6, 1, 5, 2]]])

In [17]:
np.random.seed(10)
np.random.randint(1, 4, (2, 4, 4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [18]:
np.random.seed(10)
np.random.randint(1, 4, (2, 4, 4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [20]:
2**32 -1 

4294967295

In [21]:
np.random.rand(3)

array([0.13145815, 0.41366737, 0.77872881])

In [22]:
np.random.randn(3)

array([-1.25424191,  0.33157855, -0.30860049])

In [25]:
x=[1,2,3,4,5]
np.random.choice(x)

4

In [26]:
np.random.choice(x)

5

In [27]:
np.random.choice(x)

3

In [28]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [29]:
x

[1, 2, 3, 4, 5]

In [ ]:
np.random.permutation(x)