In [93]:
import numpy as np

In [94]:
array_1d=np.arange(1,13)
print(array_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [95]:
array_even=np.arange(1,13,2)
print(array_even)

[ 1  3  5  7  9 11]


In [96]:
np.linspace(1,13,4)

array([ 1.,  5.,  9., 13.])

In [97]:
array_2d=array_1d.reshape(3,4)
print(array_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [98]:
array_3d=array_1d.reshape(2,3,2)
print(array_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [99]:
ar = np.arange(1,13).reshape(2,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [100]:
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [101]:
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [102]:
ar.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])