In [1]:
import numpy as np

In [2]:
mx_one = np.array([[1,1,1], [1,1,1], [1,1,1]])
print(mx_one)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [3]:
mx_one = np.ones(5)
print(mx_one)

[1. 1. 1. 1. 1.]


In [4]:
mx_one.dtype

dtype('float64')

In [5]:
mx_one = np.ones((3, 4))
print(mx_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
mx_one = np.ones((3, 4), dtype=int)
print(mx_one)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [7]:
mx_zero = np.zeros((4, 5))
print(mx_zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
mx_zero = np.zeros((4, 5), dtype=bool)
print(mx_zero)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


In [9]:
mx_zero = np.zeros((4, 5), dtype=str)
print(mx_zero)

[['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']
 ['' '' '' '' '']]


In [10]:
em_str = ''
print(bool(em_str))

False


In [11]:
em_str = np.empty((3, 3))
print(em_str)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
