In [3]:
import numpy as np

In [4]:
array1=np.array([1,2,3,4,5,6,7,8,9])
print(array1)

[1 2 3 4 5 6 7 8 9]


In [5]:
type(array1)

numpy.ndarray

In [6]:
array1.ndim

1

In [7]:
array2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [41]:
type(array2)

numpy.ndarray

In [42]:
array2.ndim

2

In [43]:
array1.size

9

In [44]:
array2.size

10

In [45]:
array1.shape

(9,)

In [46]:
array2.shape

(2, 5)